(cl:defpackage pp_msgs-srv
  (:use )
  (:export
   "PATHPLANNINGPLUGIN"
   "<PATHPLANNINGPLUGIN-REQUEST>"
   "PATHPLANNINGPLUGIN-REQUEST"
   "<PATHPLANNINGPLUGIN-RESPONSE>"
   "PATHPLANNINGPLUGIN-RESPONSE"
  ))

